(() => {
  const nomesMeses = ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
  const HORAS_DIA = 8;
  let dataAtual = new Date();
  let eventos = [];
  let treinamentos = [];
  let eventoEditando = null;

  function cfg() { return window.SUPABASE_CONFIG || {}; }
  function configurado() { return Boolean(cfg().url && cfg().anonKey); }
  async function supabaseFetch(path, options = {}) { if (!configurado()) throw new Error('Supabase ainda não configurado.'); const base=cfg().url.replace(/\/$/,''); const resposta=await fetch(base+'/rest/v1/'+path,{...options,headers:{apikey:cfg().anonKey,Authorization:'Bearer '+cfg().anonKey,'Content-Type':'application/json',Accept:'application/json',...(options.headers||{})}}); const texto=await resposta.text(); if(!resposta.ok)throw new Error(texto||('HTTP '+resposta.status)); return texto?JSON.parse(texto):null; }
  async function carregarEventos(){eventos=await supabaseFetch('agenda?select=*&order=data_inicio.asc,codigo.asc')||[];desenhar();}
  async function carregarTreinamentos(){treinamentos=await supabaseFetch('treinamentos?select=id,nome,norma,carga_horaria_padrao,validade_meses&ativo=eq.true&order=nome.asc')||[];}
  function iso(data){return data.getFullYear()+'-'+String(data.getMonth()+1).padStart(2,'0')+'-'+String(data.getDate()).padStart(2,'0');}
  function criarDataLocal(dataISO){if(!dataISO)return null;const p=dataISO.split('-').map(Number);return new Date(p[0],p[1]-1,p[2]);}
  function proximoDiaUtil(data){while(data.getDay()===0||data.getDay()===6)data.setDate(data.getDate()+1);return data;}
  function calcularDataFinal(){const inicio=document.getElementById('agData')?.value||'';const carga=Number(document.getElementById('agCarga')?.value||0);const campoFim=document.getElementById('agDataFim');if(!inicio||!carga||!campoFim)return;let data=proximoDiaUtil(criarDataLocal(inicio));const diasNecessarios=Math.ceil(carga/HORAS_DIA);for(let i=1;i<diasNecessarios;i++){data.setDate(data.getDate()+1);proximoDiaUtil(data);}campoFim.value=iso(data);}
  function preencherDadosTreinamento(){const id=document.getElementById('agTreinamento')?.value||'';const t=treinamentos.find(x=>String(x.id)===String(id));document.getElementById('agNorma').value=t?.norma||'';document.getElementById('agCarga').value=t?.carga_horaria_padrao??'';calcularDataFinal();}
  function preencherSelectTreinamentos(){const s=document.getElementById('agTreinamento');if(!s)return;s.innerHTML='<option value="">Selecione...</option>';treinamentos.forEach(t=>{const o=document.createElement('option');o.value=t.id;o.textContent=t.nome;s.appendChild(o);});}
  function renderStatus(){return configurado()?'<span class="status">Supabase configurado</span>':'<span class="status status-alerta">Falta configurar Supabase</span>';}
  function htmlAgenda(){return `<div class="card"><div class="agenda-topo"><div>${renderStatus()}<h2 style="margin-top:12px">📅 Agenda de Treinamentos</h2></div><div class="agenda-controles"><button class="btn" id="mesAnterior">◀</button><strong id="mesAno"></strong><button class="btn" id="mesSeguinte">▶</button></div></div><div id="avisoAgenda" class="aviso"></div><div class="agenda-semana"><div>Dom</div><div>Seg</div><div>Ter</div><div>Qua</div><div>Qui</div><div>Sex</div><div>Sáb</div></div><div id="gradeAgenda" class="agenda-grade"></div></div><div id="modalAgenda" class="modal oculto"><div class="modal-box"><h3 id="tituloModalAgenda">Novo agendamento</h3><p style="margin-top:-6px;color:#6c757d;font-size:13px">Jornada padrão: 08:00 às 13:00 e 14:00 às 17:00 (8 horas/dia).</p><div class="grid-form"><label>Data inicial<input id="agData" type="date"></label><label>Data final<input id="agDataFim" type="date" readonly></label><label>Empresa<input id="agEmpresa" type="text"></label><label>Treinamento<select id="agTreinamento"><option value="">Carregando...</option></select></label><label>Norma<input id="agNorma" type="text" readonly></label><label>Carga horária<input id="agCarga" type="number" readonly></label><label>Instrutor<input id="agInstrutor" type="text"></label><label class="full">Observação<textarea id="agObservacao"></textarea></label></div><div class="acoes"><button class="btn secundario" id="fecharAgenda">Cancelar</button><button class="btn primario" id="salvarAgenda">Salvar</button></div></div></div>`;}
  function limparModal(){eventoEditando=null;document.getElementById('tituloModalAgenda').textContent='Novo agendamento';document.getElementById('salvarAgenda').textContent='Salvar';['agEmpresa','agNorma','agCarga','agInstrutor','agObservacao'].forEach(id=>document.getElementById(id).value='');document.getElementById('agTreinamento').value='';}
  function abrirModal(dataISO){if(!configurado())return;limparModal();document.getElementById('agData').value=dataISO;document.getElementById('agDataFim').value=dataISO;document.getElementById('modalAgenda').classList.remove('oculto');}
  function localizarTreinamentoDoEvento(ev){if(ev.treinamento_id){const porId=treinamentos.find(t=>String(t.id)===String(ev.treinamento_id));if(porId)return porId;}const nome=String(ev.treinamento||'').trim().toLowerCase();return treinamentos.find(t=>String(t.nome||'').trim().toLowerCase()===nome)||null;}
  function abrirEdicao(ev){if(String(ev.status||'').toLowerCase()==='cancelado'){alert('Agendamento cancelado não pode ser editado.');return;}eventoEditando=ev;const t=localizarTreinamentoDoEvento(ev);document.getElementById('tituloModalAgenda').textContent='Editar agendamento';document.getElementById('salvarAgenda').textContent='Atualizar';document.getElementById('agData').value=ev.data_inicio||'';document.getElementById('agDataFim').value=ev.data_fim||'';document.getElementById('agEmpresa').value=ev.empresa||'';document.getElementById('agTreinamento').value=t?String(t.id):'';document.getElementById('agNorma').value=ev.norma||t?.norma||'';document.getElementById('agCarga').value=ev.carga_horaria??t?.carga_horaria_padrao??'';document.getElementById('agInstrutor').value=ev.instrutor||'';document.getElementById('agObservacao').value=ev.observacao||'';document.getElementById('modalAgenda').classList.remove('oculto');}
  function fecharModal(){document.getElementById('modalAgenda').classList.add('oculto');eventoEditando=null;}
  function filtroRegistroAgenda(ev){if(ev.id!==undefined&&ev.id!==null&&ev.id!=='')return'id=eq.'+encodeURIComponent(ev.id);if(ev.codigo)return'codigo=eq.'+encodeURIComponent(ev.codigo);throw new Error('O agendamento não possui identificador para atualização.');}
  async function cancelarAgendamento(ev){const etapa=Number(ev.etapa||1);const status=String(ev.status||'').toLowerCase();if(status==='cancelado'){alert('Este agendamento já está cancelado.');return;}if(etapa>=3){alert('Cancelamento bloqueado: já existem documentos gerados para este agendamento.');return;}const motivo=prompt('Informe o motivo do cancelamento:');if(!motivo||!motivo.trim())return;if(!confirm('Confirmar o cancelamento deste agendamento?'))return;const atual=String(ev.observacao||'').trim();const reg='[CANCELADO] '+new Date().toLocaleString('pt-BR')+' - '+motivo.trim();try{await supabaseFetch('agenda?'+filtroRegistroAgenda(ev),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status:'Cancelado',observacao:atual?atual+'\n'+reg:reg,atualizado_em:new Date().toISOString()})});await carregarEventos();}catch(e){alert('Erro ao cancelar: '+e.message);}}
  async function excluirAgendamento(ev){const etapa=Number(ev.etapa||1);const possuiTurma=Boolean(ev.id_turma);if(possuiTurma||etapa>=2){alert('Exclusão bloqueada: este agendamento já possui vínculo com turma ou etapa posterior.');return;}if(!confirm('Excluir definitivamente este agendamento? Esta ação não pode ser desfeita.'))return;try{await supabaseFetch('agenda?'+filtroRegistroAgenda(ev),{method:'DELETE'});await carregarEventos();}catch(e){alert('Erro ao excluir: '+e.message);}}
  async function salvar(){calcularDataFinal();const treinamentoId=document.getElementById('agTreinamento').value;const treinamento=treinamentos.find(t=>String(t.id)===String(treinamentoId));const dados={data_inicio:document.getElementById('agData').value,data_fim:document.getElementById('agDataFim').value,empresa:document.getElementById('agEmpresa').value.trim(),treinamento:treinamento?.nome||'',treinamento_id:treinamentoId||null,norma:document.getElementById('agNorma').value.trim()||null,carga_horaria:Number(document.getElementById('agCarga').value||0)||null,instrutor:document.getElementById('agInstrutor').value.trim(),hora_inicio:'08:00:00',hora_fim:'17:00:00',observacao:document.getElementById('agObservacao').value.trim()||null,atualizado_em:new Date().toISOString()};if(!dados.data_inicio||!dados.data_fim||!dados.empresa||!dados.treinamento_id||!dados.instrutor){alert('Preencha data, empresa, treinamento e instrutor.');return;}try{if(eventoEditando){await supabaseFetch('agenda?'+filtroRegistroAgenda(eventoEditando),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(dados)});}else{dados.codigo='AG'+Date.now();dados.status='Agendado';dados.etapa=1;await supabaseFetch('agenda',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(dados)});}fecharModal();await carregarEventos();}catch(e){alert('Erro ao salvar: '+e.message);}}
  function criarBotaoCard(icone,titulo,handler,disabled=false){const b=document.createElement('button');b.type='button';b.className='btn';b.textContent=icone;b.title=titulo;b.setAttribute('aria-label',titulo);b.disabled=disabled;b.style.width='24px';b.style.height='24px';b.style.minWidth='24px';b.style.padding='0';b.style.display='flex';b.style.alignItems='center';b.style.justifyContent='center';b.style.fontSize='12px';b.style.lineHeight='1';b.style.borderRadius='7px';b.style.opacity=disabled?'.34':'1';b.style.cursor=disabled?'not-allowed':'pointer';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(!disabled)handler();});return b;}
  function abrirTurma(ev){window.TREINAMENTO_AGENDA_SELECIONADA={...ev};const item=[...document.querySelectorAll('.menu-item')].find(x=>x.dataset.modulo==='Turmas');if(item)item.click();}
  function abrirLista(ev){if(window.abrirListaPresencaGithub){window.abrirListaPresencaGithub({...ev});}else{alert('Módulo de lista de presença ainda não carregado.');}}
  function abrirCertificados(ev){if(window.abrirCertificadosGithub){window.abrirCertificadosGithub({...ev});}else{alert('Módulo de certificados ainda não carregado.');}}
  function cardEvento(ev){const div=document.createElement('div');div.className='agenda-card';div.style.position='relative';div.style.width='94%';div.style.maxWidth='175px';div.style.marginLeft='3px';div.style.padding='5px 31px 5px 6px';div.style.minHeight='76px';div.style.fontSize='10px';div.style.lineHeight='1.1';const cancelado=String(ev.status||'').toLowerCase()==='cancelado';const etapaNumero=Number(ev.etapa||1);const possuiTurma=Boolean(ev.id_turma);const empresa=document.createElement('strong');empresa.textContent=ev.empresa||'';empresa.style.fontSize='10px';empresa.style.whiteSpace='nowrap';empresa.style.overflow='hidden';empresa.style.textOverflow='ellipsis';const treinamento=document.createElement('span');treinamento.textContent=ev.treinamento||'';treinamento.style.fontSize='10px';treinamento.style.whiteSpace='nowrap';treinamento.style.overflow='hidden';treinamento.style.textOverflow='ellipsis';const instrutor=document.createElement('small');instrutor.textContent=ev.instrutor||'';instrutor.style.fontSize='9px';instrutor.style.whiteSpace='nowrap';instrutor.style.overflow='hidden';instrutor.style.textOverflow='ellipsis';const etapa=document.createElement('div');etapa.className='etapa';etapa.textContent=cancelado?'Cancelado':'Etapa '+etapaNumero+'/4';etapa.style.marginTop='2px';etapa.style.fontSize='9px';const acoes=document.createElement('div');acoes.style.position='absolute';acoes.style.top='4px';acoes.style.right='4px';acoes.style.display='flex';acoes.style.flexDirection='column';acoes.style.gap='3px';acoes.style.zIndex='2';acoes.appendChild(criarBotaoCard('✏️','Editar agendamento',()=>abrirEdicao(ev),cancelado));acoes.appendChild(criarBotaoCard('🚫','Cancelar agendamento',()=>cancelarAgendamento(ev),cancelado||etapaNumero>=3));acoes.appendChild(criarBotaoCard('🗑️','Excluir agendamento',()=>excluirAgendamento(ev),possuiTurma||etapaNumero>=2));const fluxo=document.createElement('div');fluxo.style.marginTop='4px';fluxo.style.paddingTop='4px';fluxo.style.borderTop='1px solid #dde6e3';fluxo.style.display='flex';fluxo.style.gap='4px';fluxo.style.alignItems='center';fluxo.appendChild(criarBotaoCard('👥',possuiTurma?'Abrir turma':'Criar turma',()=>abrirTurma(ev),cancelado));fluxo.appendChild(criarBotaoCard('✅','Gerar/Abrir lista de presença',()=>abrirLista(ev),cancelado||etapaNumero<2));fluxo.appendChild(criarBotaoCard('🏅','Gerar/Abrir certificados',()=>abrirCertificados(ev),cancelado||etapaNumero<3));div.addEventListener('click',e=>e.stopPropagation());div.appendChild(empresa);div.appendChild(treinamento);div.appendChild(instrutor);div.appendChild(etapa);div.appendChild(fluxo);div.appendChild(acoes);return div;}
  function desenhar(){const grade=document.getElementById('gradeAgenda');if(!grade)return;grade.innerHTML='';document.getElementById('mesAno').textContent=nomesMeses[dataAtual.getMonth()]+' / '+dataAtual.getFullYear();const primeiro=new Date(dataAtual.getFullYear(),dataAtual.getMonth(),1);const ultimo=new Date(dataAtual.getFullYear(),dataAtual.getMonth()+1,0);for(let i=0;i<primeiro.getDay();i++)grade.appendChild(document.createElement('div')).className='agenda-dia vazio';for(let d=1;d<=ultimo.getDate();d++){const data=new Date(dataAtual.getFullYear(),dataAtual.getMonth(),d);const dataISO=iso(data);const cel=document.createElement('div');cel.className='agenda-dia';cel.innerHTML=`<div class="agenda-numero">${d}</div>`;cel.addEventListener('click',()=>abrirModal(dataISO));eventos.filter(ev=>ev.data_inicio<=dataISO&&ev.data_fim>=dataISO).forEach(ev=>cel.appendChild(cardEvento(ev)));grade.appendChild(cel);}}
  window.renderAgendaGithub=async function(){const area=document.getElementById('conteudoPrincipal');area.innerHTML=htmlAgenda();document.getElementById('mesAnterior').onclick=()=>{dataAtual.setMonth(dataAtual.getMonth()-1);desenhar();};document.getElementById('mesSeguinte').onclick=()=>{dataAtual.setMonth(dataAtual.getMonth()+1);desenhar();};document.getElementById('fecharAgenda').onclick=fecharModal;document.getElementById('salvarAgenda').onclick=salvar;document.getElementById('agData').onchange=calcularDataFinal;document.getElementById('agTreinamento').onchange=preencherDadosTreinamento;desenhar();if(!configurado()){document.getElementById('avisoAgenda').textContent='Supabase não configurado.';return;}try{await carregarTreinamentos();preencherSelectTreinamentos();await carregarEventos();}catch(e){document.getElementById('avisoAgenda').textContent='Erro ao carregar dados do Supabase: '+e.message;}};
})();