(() => {
  const nomesMeses=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
  const HORAS_DIA=8;
  let dataAtual=new Date(),eventos=[],treinamentos=[],empresas=[],instrutores=[],eventoEditando=null;
  function cfg(){return window.SUPABASE_CONFIG||{};} function configurado(){return Boolean(cfg().url&&cfg().anonKey);}
  async function supabaseFetch(path,options={}){if(!configurado())throw new Error('Supabase ainda não configurado.');const base=cfg().url.replace(/\/$/,'');const resposta=await fetch(base+'/rest/v1/'+path,{...options,headers:{apikey:cfg().anonKey,Authorization:'Bearer '+cfg().anonKey,'Content-Type':'application/json',Accept:'application/json',...(options.headers||{})}});const texto=await resposta.text();if(!resposta.ok)throw new Error(texto||('HTTP '+resposta.status));return texto?JSON.parse(texto):null;}
  async function carregarEventos(){eventos=await supabaseFetch('agenda?select=*&order=data_inicio.asc,codigo.asc')||[];desenhar();}
  async function carregarTreinamentos(){treinamentos=await supabaseFetch('treinamentos?select=id,nome,norma,carga_horaria_padrao,validade_meses&ativo=eq.true&order=nome.asc')||[];}
  async function carregarCadastros(){empresas=await supabaseFetch('empresas?select=id,nome&ativo=eq.true&order=nome.asc')||[];const is=await supabaseFetch('instrutores?select=id,pessoa_id,conselho,numero_registro,uf_registro,formacao,especialidade&ativo=eq.true')||[];const ps=await supabaseFetch('pessoas?select=id,nome&instrutor=eq.true&ativo=eq.true&order=nome.asc')||[];const nomes=new Map(ps.map(p=>[String(p.id),p.nome]));instrutores=is.map(i=>({...i,nome:nomes.get(String(i.pessoa_id))||''})).filter(i=>i.nome).sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));}
  function preencherSelect(id,lista,texto){const s=document.getElementById(id);if(!s)return;s.innerHTML='<option value="">Selecione...</option>';lista.forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x[texto];s.appendChild(o);});}
  function iso(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');} function criarDataLocal(v){if(!v)return null;const p=v.split('-').map(Number);return new Date(p[0],p[1]-1,p[2]);} function proximoDiaUtil(d){while(d.getDay()===0||d.getDay()===6)d.setDate(d.getDate()+1);return d;}
  function calcularDataFinal(){const inicio=document.getElementById('agData')?.value||'',carga=Number(document.getElementById('agCarga')?.value||0),campo=document.getElementById('agDataFim');if(!inicio||!carga||!campo)return;let d=proximoDiaUtil(criarDataLocal(inicio));for(let i=1;i<Math.ceil(carga/HORAS_DIA);i++){d.setDate(d.getDate()+1);proximoDiaUtil(d);}campo.value=iso(d);}
  function preencherDadosTreinamento(){const t=treinamentos.find(x=>String(x.id)===String(document.getElementById('agTreinamento')?.value||''));document.getElementById('agNorma').value=t?.norma||'';document.getElementById('agCarga').value=t?.carga_horaria_padrao??'';calcularDataFinal();}
  function renderStatus(){return configurado()?'<span class="status">Supabase configurado</span>':'<span class="status status-alerta">Falta configurar Supabase</span>';}
  function htmlAgenda(){return `<div class="card"><div class="agenda-topo"><div>${renderStatus()}<h2 style="margin-top:12px">📅 Agenda de Treinamentos</h2></div><div class="agenda-controles"><button class="btn" id="mesAnterior">◀</button><strong id="mesAno"></strong><button class="btn" id="mesSeguinte">▶</button></div></div><div id="avisoAgenda" class="aviso"></div><div class="agenda-semana"><div>Dom</div><div>Seg</div><div>Ter</div><div>Qua</div><div>Qui</div><div>Sex</div><div>Sáb</div></div><div id="gradeAgenda" class="agenda-grade"></div></div><div id="modalAgenda" class="modal oculto"><div class="modal-box"><h3 id="tituloModalAgenda">Novo agendamento</h3><p style="margin-top:-6px;color:#6c757d;font-size:13px">Jornada padrão: 08:00 às 13:00 e 14:00 às 17:00 (8 horas/dia).</p><div class="grid-form"><label>Data inicial<input id="agData" type="date"></label><label>Data final<input id="agDataFim" type="date" readonly></label><label>Empresa<select id="agEmpresa"><option>Carregando...</option></select></label><label>Treinamento<select id="agTreinamento"><option>Carregando...</option></select></label><label>Norma<input id="agNorma" readonly></label><label>Carga horária<input id="agCarga" type="number" readonly></label><label>Instrutor<select id="agInstrutor"><option>Carregando...</option></select></label><label class="full">Observação<textarea id="agObservacao"></textarea></label></div><div class="acoes"><button class="btn secundario" id="fecharAgenda">Cancelar</button><button class="btn primario" id="salvarAgenda">Salvar</button></div></div></div>`;}
  function limparModal(){eventoEditando=null;document.getElementById('tituloModalAgenda').textContent='Novo agendamento';document.getElementById('salvarAgenda').textContent='Salvar';['agEmpresa','agNorma','agCarga','agInstrutor','agObservacao','agTreinamento'].forEach(id=>document.getElementById(id).value='');}
  function abrirModal(dataISO){if(!configurado())return;limparModal();document.getElementById('agData').value=dataISO;document.getElementById('agDataFim').value=dataISO;document.getElementById('modalAgenda').classList.remove('oculto');}
  function abrirEdicao(ev){if(String(ev.status||'').toLowerCase()==='cancelado')return alert('Agendamento cancelado não pode ser editado.');eventoEditando=ev;document.getElementById('tituloModalAgenda').textContent='Editar agendamento';document.getElementById('salvarAgenda').textContent='Atualizar';document.getElementById('agData').value=ev.data_inicio||'';document.getElementById('agDataFim').value=ev.data_fim||'';document.getElementById('agEmpresa').value=ev.empresa_id||empresas.find(x=>x.nome===ev.empresa)?.id||'';document.getElementById('agTreinamento').value=ev.treinamento_id||treinamentos.find(x=>x.nome===ev.treinamento)?.id||'';document.getElementById('agNorma').value=ev.norma||'';document.getElementById('agCarga').value=ev.carga_horaria??'';document.getElementById('agInstrutor').value=ev.instrutor_id||instrutores.find(x=>x.nome===ev.instrutor)?.id||'';document.getElementById('agObservacao').value=ev.observacao||'';document.getElementById('modalAgenda').classList.remove('oculto');}
  function fecharModal(){document.getElementById('modalAgenda').classList.add('oculto');eventoEditando=null;} function filtroRegistroAgenda(ev){if(ev.id)return'id=eq.'+encodeURIComponent(ev.id);if(ev.codigo)return'codigo=eq.'+encodeURIComponent(ev.codigo);throw new Error('Agendamento sem identificador.');}
  async function cancelarAgendamento(ev){if(Number(ev.etapa||1)>=3)return alert('Cancelamento bloqueado: já existem documentos gerados.');const motivo=prompt('Informe o motivo do cancelamento:');if(!motivo?.trim())return;await supabaseFetch('agenda?'+filtroRegistroAgenda(ev),{method:'PATCH',body:JSON.stringify({status:'Cancelado',observacao:(ev.observacao?ev.observacao+'\n':'')+'[CANCELADO] '+motivo.trim(),atualizado_em:new Date().toISOString()})});await carregarEventos();}
  async function excluirAgendamento(ev){if(ev.id_turma||Number(ev.etapa||1)>=2)return alert('Exclusão bloqueada: este agendamento já possui turma.');if(!confirm('Excluir definitivamente este agendamento?'))return;await supabaseFetch('agenda?'+filtroRegistroAgenda(ev),{method:'DELETE'});await carregarEventos();}
  async function salvar(){calcularDataFinal();const empresa=empresas.find(x=>String(x.id)===document.getElementById('agEmpresa').value),treinamento=treinamentos.find(x=>String(x.id)===document.getElementById('agTreinamento').value),instrutor=instrutores.find(x=>String(x.id)===document.getElementById('agInstrutor').value);const dados={data_inicio:document.getElementById('agData').value,data_fim:document.getElementById('agDataFim').value,empresa:empresa?.nome||'',empresa_id:empresa?.id||null,treinamento:treinamento?.nome||'',treinamento_id:treinamento?.id||null,norma:document.getElementById('agNorma').value.trim()||null,carga_horaria:Number(document.getElementById('agCarga').value||0)||null,instrutor:instrutor?.nome||'',instrutor_id:instrutor?.id||null,hora_inicio:'08:00:00',hora_fim:'17:00:00',observacao:document.getElementById('agObservacao').value.trim()||null,atualizado_em:new Date().toISOString()};if(!dados.data_inicio||!dados.data_fim||!dados.empresa_id||!dados.treinamento_id||!dados.instrutor_id)return alert('Preencha data, empresa, treinamento e instrutor.');try{if(eventoEditando)await supabaseFetch('agenda?'+filtroRegistroAgenda(eventoEditando),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(dados)});else{dados.codigo='AG'+Date.now();dados.status='Agendado';dados.etapa=1;await supabaseFetch('agenda',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(dados)});}fecharModal();await carregarEventos();}catch(e){alert('Erro ao salvar: '+e.message);}}
  function criarBotaoCard(icone,titulo,handler,disabled=false){const b=document.createElement('button');b.type='button';b.className='btn';b.textContent=icone;b.title=titulo;b.disabled=disabled;Object.assign(b.style,{width:'24px',height:'24px',minWidth:'24px',padding:'0',display:'flex',alignItems:'center',justifyContent:'center',fontSize:'12px',borderRadius:'7px',opacity:disabled?'.34':'1'});b.onclick=e=>{e.preventDefault();e.stopPropagation();if(!disabled)handler();};return b;}
  function abrirTurma(ev){window.TREINAMENTO_AGENDA_SELECIONADA={...ev};[...document.querySelectorAll('.menu-item')].find(x=>x.dataset.modulo==='Turmas')?.click();} function abrirLista(ev){window.abrirListaPresencaGithub?window.abrirListaPresencaGithub({...ev}):alert('Módulo de lista não carregado.');} function abrirCertificados(ev){window.abrirCertificadosGithub?window.abrirCertificadosGithub({...ev}):alert('Módulo de certificados não carregado.');}
  function cardEvento(ev){const div=document.createElement('div');div.className='agenda-card';Object.assign(div.style,{position:'relative',width:'94%',maxWidth:'175px',marginLeft:'3px',padding:'5px 31px 5px 6px',minHeight:'76px',fontSize:'10px'});const cancelado=String(ev.status||'').toLowerCase()==='cancelado',etapa=Number(ev.etapa||1),possui=Boolean(ev.id_turma);div.innerHTML=`<strong>${ev.empresa||''}</strong><span>${ev.treinamento||''}</span><small>${ev.instrutor||''}</small><div class="etapa">${cancelado?'Cancelado':'Etapa '+etapa+'/4'}</div>`;const fluxo=document.createElement('div');Object.assign(fluxo.style,{display:'flex',gap:'4px',marginTop:'4px'});fluxo.append(criarBotaoCard('👥',possui?'Abrir turma':'Criar turma',()=>abrirTurma(ev),cancelado),criarBotaoCard('✅','Lista de presença',()=>abrirLista(ev),cancelado||etapa<2),criarBotaoCard('🏅','Certificados',()=>abrirCertificados(ev),cancelado||etapa<3));const acoes=document.createElement('div');Object.assign(acoes.style,{position:'absolute',right:'4px',top:'4px',display:'flex',flexDirection:'column',gap:'3px'});acoes.append(criarBotaoCard('✏️','Editar',()=>abrirEdicao(ev),cancelado),criarBotaoCard('🚫','Cancelar',()=>cancelarAgendamento(ev),cancelado||etapa>=3),criarBotaoCard('🗑️','Excluir',()=>excluirAgendamento(ev),possui||etapa>=2));div.append(fluxo,acoes);div.onclick=e=>e.stopPropagation();return div;}
  function desenhar(){const grade=document.getElementById('gradeAgenda');if(!grade)return;grade.innerHTML='';document.getElementById('mesAno').textContent=nomesMeses[dataAtual.getMonth()]+' / '+dataAtual.getFullYear();const primeiro=new Date(dataAtual.getFullYear(),dataAtual.getMonth(),1),ultimo=new Date(dataAtual.getFullYear(),dataAtual.getMonth()+1,0);for(let i=0;i<primeiro.getDay();i++)grade.appendChild(document.createElement('div')).className='agenda-dia vazio';for(let d=1;d<=ultimo.getDate();d++){const data=iso(new Date(dataAtual.getFullYear(),dataAtual.getMonth(),d)),cel=document.createElement('div');cel.className='agenda-dia';cel.innerHTML=`<div class="agenda-numero">${d}</div>`;cel.onclick=()=>abrirModal(data);eventos.filter(e=>e.data_inicio<=data&&e.data_fim>=data).forEach(e=>cel.appendChild(cardEvento(e)));grade.appendChild(cel);}}
  window.renderAgendaGithub=async function(){const area=document.getElementById('conteudoPrincipal');area.innerHTML=htmlAgenda();document.getElementById('mesAnterior').onclick=()=>{dataAtual.setMonth(dataAtual.getMonth()-1);desenhar();};document.getElementById('mesSeguinte').onclick=()=>{dataAtual.setMonth(dataAtual.getMonth()+1);desenhar();};document.getElementById('fecharAgenda').onclick=fecharModal;document.getElementById('salvarAgenda').onclick=salvar;document.getElementById('agData').onchange=calcularDataFinal;document.getElementById('agTreinamento').onchange=preencherDadosTreinamento;desenhar();if(!configurado())return;try{await Promise.all([carregarTreinamentos(),carregarCadastros()]);preencherSelect('agTreinamento',treinamentos,'nome');preencherSelect('agEmpresa',empresas,'nome');preencherSelect('agInstrutor',instrutores,'nome');await carregarEventos();}catch(e){document.getElementById('avisoAgenda').textContent='Erro ao carregar dados: '+e.message;}};
})();