(() => {
  function cfg(){return window.SUPABASE_CONFIG||{};}
  function configurado(){return Boolean(cfg().url&&cfg().anonKey);}
  async function supabaseFetch(path,options={}){if(!configurado())throw new Error('Supabase ainda não configurado.');const base=cfg().url.replace(/\/$/,'');const r=await fetch(base+'/rest/v1/'+path,{...options,headers:{apikey:cfg().anonKey,Authorization:'Bearer '+cfg().anonKey,'Content-Type':'application/json',Accept:'application/json',...(options.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(t||('HTTP '+r.status));return t?JSON.parse(t):null;}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function dataBr(v){if(!v)return'';const p=String(v).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:String(v);}
  function cpf(v){const d=String(v||'').replace(/\D/g,'').padStart(11,'0').slice(-11);return d.replace(/^(\d{3})(\d{3})(\d{3})(\d{2})$/,'$1.$2.$3-$4');}
  function fechar(){document.getElementById('modalCertificados')?.remove();}
  async function carregar(ev){if(!ev?.id_turma)throw new Error('Este agendamento ainda não possui turma.');const ts=await supabaseFetch('turmas?id=eq.'+encodeURIComponent(ev.id_turma)+'&select=*&limit=1');if(!ts?.length)throw new Error('Turma não encontrada.');const turma=ts[0];const participantes=await supabaseFetch('turma_participantes?turma_id=eq.'+encodeURIComponent(turma.id)+'&select=nome,cpf&order=nome.asc')||[];if(!participantes.length)throw new Error('A turma não possui participantes.');let identidade=window.TREINAMENTO_IDENTIDADE_EMPRESA||null;if(!identidade){const ids=await supabaseFetch('configuracao_empresa?ativo=eq.true&select=*&limit=1');identidade=ids?.[0]||null;}return{turma,participantes,identidade};}
  function htmlCertificado(turma,p,identidade){const cor=identidade?.cor_principal||'#0b8f43';const logo=identidade?.logo_url?`<img src="${esc(identidade.logo_url)}" style="max-width:180px;max-height:80px;object-fit:contain">`:'';return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Certificado - ${esc(p.nome)}</title><style>@page{size:A4 landscape;margin:12mm}*{box-sizing:border-box}body{margin:0;font-family:Georgia,serif;color:#1f2937}.cert{min-height:180mm;border:8px double ${cor};padding:22mm;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center}.logo{margin-bottom:12px}.titulo{font-size:34px;color:${cor};font-weight:700;letter-spacing:1px}.texto{font-family:Arial,sans-serif;font-size:18px;line-height:1.7;max-width:900px}.nome{font-size:30px;font-weight:700;margin:12px 0}.rodape{margin-top:24px;font-family:Arial,sans-serif;font-size:13px}.assinatura{margin-top:35px;border-top:1px solid #333;width:320px;padding-top:6px;font-family:Arial,sans-serif;font-size:13px}@media print{button{display:none}}</style></head><body><div class="cert"><div class="logo">${logo}</div><div class="titulo">CERTIFICADO</div><p class="texto">Certificamos que</p><div class="nome">${esc(p.nome)}</div><p class="texto">CPF ${esc(cpf(p.cpf))}, participou do treinamento <strong>${esc(turma.treinamento||'')}</strong>, promovido para <strong>${esc(turma.empresa||'')}</strong>, realizado de ${esc(dataBr(turma.data_inicio))} a ${esc(dataBr(turma.data_fim))}, com carga horária de <strong>${esc(turma.carga_horaria||'')} horas</strong>.</p><div class="assinatura">${esc(turma.instrutor||'')}<br>${esc([turma.habilitacao_instrutor,turma.registro_instrutor].filter(Boolean).join(' - '))}</div><div class="rodape">${esc(identidade?.nome_exibicao||'')}</div></div><script>window.onload=()=>window.print();<\/script></body></html>`;}
  function render(ev,turma,participantes,identidade){fechar();const modal=document.createElement('div');modal.id='modalCertificados';modal.className='modal';const linhas=participantes.map((p,i)=>`<tr><td>${i+1}</td><td>${esc(p.nome)}</td><td>${esc(cpf(p.cpf))}</td><td><button class="btn btnCertIndividual" data-i="${i}">🏅 Visualizar</button></td></tr>`).join('');modal.innerHTML=`<div class="modal-box" style="width:min(980px,97vw)"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><h3 style="margin:0">🏅 Certificados</h3><button class="btn" id="fecharCertificados">✕</button></div><div class="aviso" style="color:#46505a">Prévia dos certificados da turma. O layout final ainda poderá ser refinado.</div><div class="grid-form"><label>Empresa<input readonly value="${esc(turma.empresa||'')}"></label><label>Treinamento<input readonly value="${esc(turma.treinamento||'')}"></label><label>Instrutor<input readonly value="${esc(turma.instrutor||'')}"></label><label>Participantes<input readonly value="${participantes.length}"></label></div><div style="overflow:auto;max-height:48vh;margin-top:12px"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Nº</th><th>Nome</th><th>CPF</th><th>Ação</th></tr></thead><tbody>${linhas}</tbody></table></div><div class="acoes"><button class="btn secundario" id="voltarCertificados">Voltar</button><button class="btn primario" id="concluirCertificados">Concluir certificados</button></div></div>`;document.body.appendChild(modal);modal.querySelectorAll('th,td').forEach(x=>{x.style.border='1px solid #dde6e3';x.style.padding='7px'});document.getElementById('fecharCertificados').onclick=fechar;document.getElementById('voltarCertificados').onclick=fechar;modal.querySelectorAll('.btnCertIndividual').forEach(b=>b.onclick=()=>{const p=participantes[Number(b.dataset.i)];const w=window.open('','_blank');if(!w){alert('O navegador bloqueou a janela de impressão.');return;}w.document.write(htmlCertificado(turma,p,identidade));w.document.close();});document.getElementById('concluirCertificados').onclick=async()=>{try{const filtro=ev.id?'id=eq.'+encodeURIComponent(ev.id):'codigo=eq.'+encodeURIComponent(ev.codigo);await supabaseFetch('agenda?'+filtro,{method:'PATCH',body:JSON.stringify({etapa:4,status:'Concluído',atualizado_em:new Date().toISOString()})});fechar();alert('Certificados concluídos. A Agenda avançou para a etapa 4.');if(window.renderAgendaGithub)await window.renderAgendaGithub();}catch(e){alert('Erro ao concluir certificados: '+e.message);}};}
  window.abrirCertificadosGithub=async function(ev){try{const d=await carregar(ev);render(ev,d.turma,d.participantes,d.identidade);}catch(e){alert('Erro ao abrir certificados: '+e.message);}};
})();