(() => {
  function cfg(){return window.SUPABASE_CONFIG||{};}
  function configurado(){return Boolean(cfg().url&&cfg().anonKey);}
  async function supabaseFetch(path,options={}){if(!configurado())throw new Error('Supabase ainda não configurado.');const base=cfg().url.replace(/\/$/,'');const r=await fetch(base+'/rest/v1/'+path,{...options,headers:{apikey:cfg().anonKey,Authorization:'Bearer '+cfg().anonKey,'Content-Type':'application/json',Accept:'application/json',...(options.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(t||('HTTP '+r.status));return t?JSON.parse(t):null;}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  let registro=null;
  async function carregar(){const rows=await supabaseFetch('configuracao_empresa?ativo=eq.true&select=*&limit=1');registro=rows?.[0]||null;return registro;}
  function campo(id,label,valor='',tipo='text'){return `<label>${label}<input id="${id}" type="${tipo}" value="${esc(valor)}"></label>`;}
  function html(c){return `<div class="card" style="max-width:1000px"><span class="status">Personalização do sistema</span><h2 style="margin-top:12px">⚙️ Identidade da Empresa</h2><p style="color:#6c757d">Estes dados serão usados nos documentos emitidos pelo sistema. A empresa do sistema é diferente do cliente/fazenda atendido.</p><div class="grid-form">${campo('cfgNome','Nome exibido *',c?.nome_exibicao||'')}${campo('cfgSubtitulo','Subtítulo',c?.subtitulo||'')}${campo('cfgTelefone','Telefone',c?.telefone||'')}${campo('cfgWhatsapp','WhatsApp',c?.whatsapp||'')}${campo('cfgEmail','E-mail',c?.email||'','email')}${campo('cfgCor','Cor principal',c?.cor_principal||'#0b8f43','color')}<label class="full">Endereço<input id="cfgEndereco" value="${esc(c?.endereco||'')}"></label><label class="full">Logo - URL pública<input id="cfgLogo" type="url" placeholder="https://..." value="${esc(c?.logo_url||'')}"></label><label class="full">Imagem de rodapé - URL pública<input id="cfgRodape" type="url" placeholder="https://..." value="${esc(c?.rodape_url||'')}"><small style="display:block;margin-top:5px;color:#6c757d;font-weight:normal">Use uma imagem horizontal própria para o rodapé dos documentos.</small></label></div><div id="previewIdentidade" style="margin-top:18px;border:1px solid #dde6e3;border-radius:12px;padding:16px;min-height:100px"></div><div id="avisoConfiguracao" class="aviso"></div><div class="acoes"><button class="btn primario" id="salvarConfiguracao">Salvar identidade</button></div></div>`;}
  function atualizarPreview(){const box=document.getElementById('previewIdentidade');if(!box)return;const logo=document.getElementById('cfgLogo').value.trim();const rodape=document.getElementById('cfgRodape').value.trim();const nome=document.getElementById('cfgNome').value.trim()||'Nome da empresa';const sub=document.getElementById('cfgSubtitulo').value.trim();box.innerHTML=`<div style="display:flex;gap:18px;align-items:center">${logo?`<img src="${esc(logo)}" alt="Logo" style="max-width:180px;max-height:80px;object-fit:contain" onerror="this.style.display='none'">`:'<div style="width:130px;height:60px;border:1px dashed #b8c4c0;border-radius:8px;display:flex;align-items:center;justify-content:center;color:#89938f">LOGO</div>'}<div><strong style="font-size:20px">${esc(nome)}</strong>${sub?`<div style="margin-top:5px;color:#6c757d">${esc(sub)}</div>`:''}</div></div>${rodape?`<div style="margin-top:16px;padding-top:12px;border-top:1px solid #dde6e3"><div style="font-size:12px;color:#6c757d;margin-bottom:6px">Prévia do rodapé</div><img src="${esc(rodape)}" alt="Rodapé" style="width:100%;max-height:100px;object-fit:contain;object-position:left center" onerror="this.style.display='none'"></div>`:''}`;}
  async function salvar(){const nome=document.getElementById('cfgNome').value.trim();if(!nome){alert('Informe o nome exibido da empresa.');return;}const dados={nome_exibicao:nome,subtitulo:document.getElementById('cfgSubtitulo').value.trim()||null,telefone:document.getElementById('cfgTelefone').value.trim()||null,whatsapp:document.getElementById('cfgWhatsapp').value.trim()||null,email:document.getElementById('cfgEmail').value.trim()||null,endereco:document.getElementById('cfgEndereco').value.trim()||null,logo_url:document.getElementById('cfgLogo').value.trim()||null,rodape_url:document.getElementById('cfgRodape').value.trim()||null,cor_principal:document.getElementById('cfgCor').value||'#0b8f43',ativo:true,atualizado_em:new Date().toISOString()};try{let retorno;if(registro?.id){retorno=await supabaseFetch('configuracao_empresa?id=eq.'+encodeURIComponent(registro.id),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(dados)});}else{retorno=await supabaseFetch('configuracao_empresa',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(dados)});}registro=retorno?.[0]||registro||dados;document.getElementById('avisoConfiguracao').textContent='Identidade salva com sucesso.';window.TREINAMENTO_IDENTIDADE_EMPRESA=registro;atualizarPreview();}catch(e){document.getElementById('avisoConfiguracao').textContent='Erro ao salvar: '+e.message;}}
  window.carregarIdentidadeEmpresaGithub=async function(){try{const c=await carregar();window.TREINAMENTO_IDENTIDADE_EMPRESA=c;return c;}catch(e){console.warn('Identidade da empresa não carregada:',e);return null;}};
  window.renderConfiguracoesGithub=async function(){const area=document.getElementById('conteudoPrincipal');if(!configurado()){area.innerHTML='<div class="card"><h2>⚙️ Configurações</h2><div class="aviso">Supabase não configurado.</div></div>';return;}try{const c=await carregar();area.innerHTML=html(c);['cfgNome','cfgSubtitulo','cfgLogo','cfgRodape'].forEach(id=>document.getElementById(id).addEventListener('input',atualizarPreview));document.getElementById('salvarConfiguracao').onclick=salvar;atualizarPreview();}catch(e){area.innerHTML=`<div class="card"><h2>⚙️ Identidade da Empresa</h2><div class="aviso">Erro ao carregar configuração: ${esc(e.message)}</div><p>Execute as migrations 004 e 005 no Supabase.</p></div>`;}};
})();