(() => {
  function cfg(){return window.SUPABASE_CONFIG||{};}
  function configurado(){return Boolean(cfg().url&&cfg().anonKey);}
  async function supabaseFetch(path,options={}){
    if(!configurado()) throw new Error('Supabase ainda não configurado.');
    const base=cfg().url.replace(/\/$/,'');
    const r=await fetch(base+'/rest/v1/'+path,{...options,headers:{apikey:cfg().anonKey,Authorization:'Bearer '+cfg().anonKey,'Content-Type':'application/json',Accept:'application/json',...(options.headers||{})}});
    const t=await r.text();
    if(!r.ok) throw new Error(t||('HTTP '+r.status));
    return t?JSON.parse(t):null;
  }
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();}
  function cpfNum(v){return String(v||'').replace(/\D/g,'');}
  function cpfMask(v){const d=cpfNum(v);return d.length===11?d.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/,'$1.$2.$3-$4'):v||'';}
  function dataHora(v){if(!v)return'';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleDateString('pt-BR')+' '+d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});}
  let dados=[];
  function html(){return `<div class="card"><h2>📂 Histórico de Documentos</h2><div class="grid-3"><label>Empresa<input id="histEmpresa" placeholder="Digite parte da empresa"></label><label>Treinamento<input id="histTreinamento" placeholder="Digite parte do treinamento"></label><label>Tipo<select id="histTipo"><option value="">Todos</option><option value="Certificado">Certificado</option><option value="Lista de Presença">Lista de Presença</option></select></label></div><div class="grid-3"><label>Turma<input id="histTurma" placeholder="Código da turma"></label><label>Participante<input id="histParticipante" placeholder="Nome do participante"></label><label>CPF<input id="histCpf" placeholder="CPF"></label></div><div style="display:flex;gap:8px;margin-top:8px"><button class="btn primario" id="btnHistPesquisar">🔍 Pesquisar</button><button class="btn" id="btnHistLimpar">🧹 Limpar</button></div><div id="histMsg" class="aviso"></div><div style="overflow:auto;margin-top:16px"><table style="width:100%;border-collapse:collapse;min-width:980px"><thead><tr><th>Turma</th><th>Data/Hora</th><th>Tipo</th><th>Empresa</th><th>Treinamento</th><th>Participante</th><th>CPF</th><th>Status</th><th>Ações</th></tr></thead><tbody id="histBody"></tbody></table></div></div>`;}
  function filtrar(){const f={empresa:norm(document.getElementById('histEmpresa').value),treinamento:norm(document.getElementById('histTreinamento').value),tipo:norm(document.getElementById('histTipo').value),turma:norm(document.getElementById('histTurma').value),participante:norm(document.getElementById('histParticipante').value),cpf:cpfNum(document.getElementById('histCpf').value)};const out=dados.filter(x=>(!f.empresa||norm(x.empresa).includes(f.empresa))&&(!f.treinamento||norm(x.treinamento).includes(f.treinamento))&&(!f.tipo||norm(x.tipo)===f.tipo)&&(!f.turma||norm(x.id_turma).includes(f.turma))&&(!f.participante||norm(x.participante).includes(f.participante))&&(!f.cpf||cpfNum(x.cpf).includes(f.cpf)));render(out);}
  function render(lista){const tb=document.getElementById('histBody');tb.innerHTML='';if(!lista.length){tb.innerHTML='<tr><td colspan="9" style="text-align:center;padding:18px">Nenhum registro encontrado.</td></tr>';document.getElementById('histMsg').textContent='Nenhum registro encontrado.';return;}lista.forEach(x=>{const tr=document.createElement('tr');const acao=x.arquivo_url?`<button class="btn" data-url="${esc(x.arquivo_url)}">📂 Abrir</button>`:'<span style="color:#8a9299">Local</span>';tr.innerHTML=`<td>${esc(x.id_turma||'')}</td><td>${esc(dataHora(x.criado_em))}</td><td>${x.tipo==='Certificado'?'📜 ':x.tipo==='Lista de Presença'?'📋 ':''}${esc(x.tipo||'')}</td><td>${esc(x.empresa||'')}</td><td>${esc(x.treinamento||'')}</td><td>${esc(x.participante||'')}</td><td>${esc(cpfMask(x.cpf))}</td><td>${esc(x.status||'Gerado')}</td><td>${acao}</td>`;tr.querySelectorAll('td').forEach(td=>{td.style.border='1px solid #dde6e3';td.style.padding='7px'});const b=tr.querySelector('button[data-url]');if(b)b.onclick=()=>window.open(b.dataset.url,'_blank');tb.appendChild(tr);});document.getElementById('histMsg').textContent=lista.length+' registro(s) encontrado(s).';}
  async function carregar(){dados=await supabaseFetch('historico_documentos?select=*&order=criado_em.desc&limit=1000')||[];filtrar();}
  window.registrarHistoricoDocumentoGithub=async function(item){try{return await supabaseFetch('historico_documentos',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(item)});}catch(e){console.warn('Falha ao registrar histórico:',e);return null;}};
  window.renderHistoricoGithub=async function(){const area=document.getElementById('conteudoPrincipal');area.innerHTML=html();document.getElementById('btnHistPesquisar').onclick=filtrar;document.getElementById('btnHistLimpar').onclick=()=>{['histEmpresa','histTreinamento','histTurma','histParticipante','histCpf'].forEach(id=>document.getElementById(id).value='');document.getElementById('histTipo').value='';filtrar();};['histEmpresa','histTreinamento','histTurma','histParticipante','histCpf'].forEach(id=>document.getElementById(id).addEventListener('keydown',e=>{if(e.key==='Enter')filtrar();}));try{await carregar();}catch(e){document.getElementById('histMsg').textContent='Erro ao carregar histórico: '+e.message;render([]);}};
})();