(() => {
  function cfg(){return window.SUPABASE_CONFIG||{};}
  function configurado(){return Boolean(cfg().url&&cfg().anonKey);}
  async function supabaseFetch(path,options={}){if(!configurado())throw new Error('Supabase ainda não configurado.');const base=cfg().url.replace(/\/$/,'');const r=await fetch(base+'/rest/v1/'+path,{...options,headers:{apikey:cfg().anonKey,Authorization:'Bearer '+cfg().anonKey,'Content-Type':'application/json',Accept:'application/json',...(options.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(t||('HTTP '+r.status));return t?JSON.parse(t):null;}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  let treinamentos=[];let editando=null;
  async function carregar(){treinamentos=await supabaseFetch('treinamentos?select=id,nome,norma,carga_horaria_padrao,validade_meses,descricao,topicos_padrao,ativo&order=nome.asc')||[];}
  function tela(){return `<div class="card"><button class="btn" id="trVoltar">← Cadastros</button><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;margin-top:16px"><div><h2 style="margin:0">📚 Treinamentos</h2><p style="color:#6c757d;margin-bottom:0">Cadastre o treinamento uma vez e reutilize na Agenda e nas Turmas.</p></div><button class="btn primario" id="trNovo">+ Novo treinamento</button></div><div style="margin-top:18px"><input id="trBusca" placeholder="Buscar por nome ou norma" style="max-width:360px"><div id="trLista" style="margin-top:14px"></div></div></div><div id="trModal" class="modal oculto"><div class="modal-box" style="width:min(820px,96vw)"><h3 id="trTitulo">Novo treinamento</h3><div class="grid-form"><label>Nome *<input id="trNome"></label><label>Norma<input id="trNorma" placeholder="Ex.: NR-35"></label><label>Carga horária padrão (h) *<input id="trCarga" type="number" min="0.5" step="0.5"></label><label>Validade (meses)<input id="trValidade" type="number" min="1" step="1" placeholder="Vazio = sem validade"></label><label class="full">Descrição<textarea id="trDescricao" rows="3"></textarea></label><label class="full">Conteúdo programático padrão<textarea id="trTopicos" rows="9" placeholder="Digite um tópico por linha"></textarea><small style="display:block;margin-top:5px;color:#6c757d;font-weight:normal">Ao criar a turma, esse conteúdo será copiado para o histórico da turma.</small></label></div><div id="trAviso" class="aviso"></div><div class="acoes"><button class="btn secundario" id="trCancelar">Cancelar</button><button class="btn primario" id="trSalvar">Salvar</button></div></div></div>`;}
  function renderLista(filtro=''){const box=document.getElementById('trLista');const q=filtro.trim().toLowerCase();const itens=treinamentos.filter(t=>!q||String(t.nome||'').toLowerCase().includes(q)||String(t.norma||'').toLowerCase().includes(q));if(!itens.length){box.innerHTML='<div style="color:#6c757d;padding:12px 0">Nenhum treinamento encontrado.</div>';return;}box.innerHTML=`<div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr style="text-align:left"><th style="padding:9px;border-bottom:1px solid #dde6e3">Treinamento</th><th style="padding:9px;border-bottom:1px solid #dde6e3">Norma</th><th style="padding:9px;border-bottom:1px solid #dde6e3">Carga</th><th style="padding:9px;border-bottom:1px solid #dde6e3">Validade</th><th style="padding:9px;border-bottom:1px solid #dde6e3;width:90px"></th></tr></thead><tbody>${itens.map(t=>`<tr><td style="padding:9px;border-bottom:1px solid #eef2f1">${esc(t.nome)}</td><td style="padding:9px;border-bottom:1px solid #eef2f1">${esc(t.norma||'')}</td><td style="padding:9px;border-bottom:1px solid #eef2f1">${esc(t.carga_horaria_padrao??'')} h</td><td style="padding:9px;border-bottom:1px solid #eef2f1">${t.validade_meses?esc(t.validade_meses)+' meses':'-'}</td><td style="padding:9px;border-bottom:1px solid #eef2f1"><button class="btn trEditar" data-id="${esc(t.id)}" style="padding:6px 9px">Editar</button></td></tr>`).join('')}</tbody></table></div>`;box.querySelectorAll('.trEditar').forEach(b=>b.onclick=()=>abrirEdicao(b.dataset.id));}
  function limpar(){editando=null;['trNome','trNorma','trCarga','trValidade','trDescricao','trTopicos'].forEach(id=>document.getElementById(id).value='');document.getElementById('trTitulo').textContent='Novo treinamento';document.getElementById('trAviso').textContent='';}
  function abrirNovo(){limpar();document.getElementById('trModal').classList.remove('oculto');document.getElementById('trNome').focus();}
  function abrirEdicao(id){limpar();const t=treinamentos.find(x=>String(x.id)===String(id));if(!t)return;editando=t;document.getElementById('trTitulo').textContent='Editar treinamento';document.getElementById('trNome').value=t.nome||'';document.getElementById('trNorma').value=t.norma||'';document.getElementById('trCarga').value=t.carga_horaria_padrao??'';document.getElementById('trValidade').value=t.validade_meses??'';document.getElementById('trDescricao').value=t.descricao||'';document.getElementById('trTopicos').value=t.topicos_padrao||'';document.getElementById('trModal').classList.remove('oculto');}
  function fechar(){document.getElementById('trModal').classList.add('oculto');}
  async function salvar(){const nome=document.getElementById('trNome').value.trim();const carga=Number(document.getElementById('trCarga').value||0);const validadeTxt=document.getElementById('trValidade').value.trim();if(!nome){document.getElementById('trAviso').textContent='Informe o nome do treinamento.';return;}if(!carga||carga<=0){document.getElementById('trAviso').textContent='Informe uma carga horária válida.';return;}const dados={nome,norma:document.getElementById('trNorma').value.trim()||null,carga_horaria_padrao:carga,validade_meses:validadeTxt?Number(validadeTxt):null,descricao:document.getElementById('trDescricao').value.trim()||null,topicos_padrao:document.getElementById('trTopicos').value.trim()||null,ativo:true,atualizado_em:new Date().toISOString()};try{if(editando){await supabaseFetch('treinamentos?id=eq.'+encodeURIComponent(editando.id),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(dados)});}else{await supabaseFetch('treinamentos',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(dados)});}fechar();await carregar();renderLista(document.getElementById('trBusca').value);}catch(e){const m=String(e.message||'');document.getElementById('trAviso').textContent=m.includes('uq_treinamentos_nome')?'Já existe um treinamento com este nome.':'Erro ao salvar: '+m;}}
  window.renderTreinamentosGithub=async function(){const area=document.getElementById('conteudoPrincipal');area.innerHTML=tela();document.getElementById('trVoltar').onclick=()=>window.renderCadastrosGithub();document.getElementById('trNovo').onclick=abrirNovo;document.getElementById('trCancelar').onclick=fechar;document.getElementById('trSalvar').onclick=salvar;document.getElementById('trBusca').oninput=e=>renderLista(e.target.value);try{await carregar();renderLista();}catch(e){document.getElementById('trLista').innerHTML='<div class="aviso">Erro ao carregar treinamentos: '+esc(e.message)+'<br>Execute a migration 009 no Supabase.</div>';}};
  const renderAnterior=window.renderCadastrosGithub;
  if(renderAnterior){window.renderCadastrosGithub=async function(){await renderAnterior();const botoes=[...document.querySelectorAll('#conteudoPrincipal button.card')];const treinamento=botoes.find(b=>b.textContent.includes('Treinamentos'));if(treinamento){treinamento.disabled=false;treinamento.style.opacity='1';treinamento.innerHTML='<strong style="font-size:17px">📚 Treinamentos</strong><div style="font-size:12px;color:#6c757d;margin-top:6px">Cursos, normas e conteúdo</div>';treinamento.onclick=window.renderTreinamentosGithub;}};}
})();