-- Treinamento 2.0 - Agenda
create table if not exists public.agenda (
  id bigint generated by default as identity primary key,
  codigo text unique,
  data_inicio date not null,
  data_fim date not null,
  empresa text not null,
  treinamento text not null,
  norma text,
  carga_horaria numeric(6,2),
  instrutor text not null,
  hora_inicio time,
  hora_fim time,
  status text not null default 'Agendado',
  etapa integer not null default 1 check (etapa between 1 and 4),
  observacao text,
  id_turma text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

alter table public.agenda enable row level security;

-- Política temporária para teste do GitHub Pages.
-- Depois será substituída por política baseada em autenticação.
drop policy if exists "agenda_select_public" on public.agenda;
create policy "agenda_select_public" on public.agenda
for select to anon using (true);

drop policy if exists "agenda_insert_public" on public.agenda;
create policy "agenda_insert_public" on public.agenda
for insert to anon with check (true);

drop policy if exists "agenda_update_public" on public.agenda;
create policy "agenda_update_public" on public.agenda
for update to anon using (true) with check (true);

drop policy if exists "agenda_delete_public" on public.agenda;
create policy "agenda_delete_public" on public.agenda
for delete to anon using (true);
