create table if not exists public.configuracao_empresa (
  id bigint generated by default as identity primary key,
  nome_exibicao text not null,
  subtitulo text,
  telefone text,
  whatsapp text,
  email text,
  endereco text,
  logo_url text,
  cor_principal text default '#0b8f43',
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create unique index if not exists configuracao_empresa_um_ativo
  on public.configuracao_empresa ((ativo))
  where ativo = true;

alter table public.configuracao_empresa enable row level security;

drop policy if exists configuracao_empresa_select_temp on public.configuracao_empresa;
create policy configuracao_empresa_select_temp
on public.configuracao_empresa for select
to anon
using (true);

drop policy if exists configuracao_empresa_insert_temp on public.configuracao_empresa;
create policy configuracao_empresa_insert_temp
on public.configuracao_empresa for insert
to anon
with check (true);

drop policy if exists configuracao_empresa_update_temp on public.configuracao_empresa;
create policy configuracao_empresa_update_temp
on public.configuracao_empresa for update
to anon
using (true)
with check (true);

comment on table public.configuracao_empresa is 'Identidade visual e dados institucionais da empresa usuária do sistema.';
comment on column public.configuracao_empresa.logo_url is 'URL pública do logotipo. Futuramente poderá apontar para Supabase Storage.';